FROM ubuntu:26.10
WORKDIR /usr/local/app


# Install apt packages
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        gpiod \
        build-essential \
        swig  \
        python3-lgpio \
        liblgpio-dev \
        python3-dev \
        python3.14-venv \
        python3-setuptools \
        python3-pip \
        unzip wget && \
    rm -rf /var/lib/apt/lists/*


#RUN wget http://abyz.me.uk/lg/lg.zip
#RUN unzip lg.zip
#RUN cd lg
#RUN make
#RUN sudo make install



# 1. Define the venv path
ENV VIRTUAL_ENV=/opt/venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# 2. Create the virtual environment
RUN python3 -m venv $VIRTUAL_ENV

# 3. Install dependencies (pip now uses the venv automatically)
#RUN source /venv/bin/activate
RUN pip install rpi-lgpio


# 4. Run the app
COPY src ./src
CMD ["python3", "src/rpi_sense.py"]
